/**
 * X Sender — OAuth 2.0 PKCE flow (stub)
 *
 * This app manages the OAuth 2.0 PKCE flow for X API authentication.
 * In Phase 0 the Keychain read/write is stubbed with TODO comments;
 * replace each TODO section with the actual platform Keychain API when
 * integrating with AKARI Shell's Permission API.
 *
 * Flow (spec §7.1):
 *   1. Shell triggers Permission API → user approves
 *   2. This app generates PKCE code_verifier + code_challenge
 *   3. Browser opens X OAuth 2.0 authorization URL
 *   4. Callback receives authorization_code → exchanges for tokens
 *   5. Tokens saved to Keychain (service: "com.akari.example.x-sender")
 *   6. Subsequent requests use access_token; refresh automatically on expiry
 *
 * Keychain layout (spec §7.2):
 *   service = "com.akari.example.x-sender"
 *   accounts:
 *     "access_token"   → Bearer token
 *     "refresh_token"  → Refresh token
 *     "token_expiry"   → ISO 8601 UTC string
 */

import * as crypto from "crypto";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const X_OAUTH_AUTHORIZE_URL = "https://twitter.com/i/oauth2/authorize";
// Referenced by TODO stubs in exchangeCodeForToken / refreshAccessToken.
// Exported to survive noUnusedLocals until the stubs are implemented.
export const X_OAUTH_TOKEN_URL = "https://api.twitter.com/2/oauth2/token";

const KEYCHAIN_SERVICE = "com.akari.example.x-sender";
const KEYCHAIN_ACCOUNT_ACCESS_TOKEN = "access_token";
const KEYCHAIN_ACCOUNT_REFRESH_TOKEN = "refresh_token";
const KEYCHAIN_ACCOUNT_TOKEN_EXPIRY = "token_expiry";

// OAuth 2.0 scopes required by the MCP tools in this app
const OAUTH_SCOPES = [
  "tweet.read",
  "tweet.write",
  "users.read",
  "offline.access", // enables refresh_token issuance
];

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface TokenSet {
  access_token: string;
  refresh_token: string;
  expires_at: string; // ISO 8601 UTC
}

export interface PKCEParams {
  code_verifier: string;
  code_challenge: string;
  state: string;
}

// ---------------------------------------------------------------------------
// PKCE helpers
// ---------------------------------------------------------------------------

/**
 * Generate a PKCE code_verifier (43–128 chars, URL-safe Base64).
 * Spec: RFC 7636
 */
export function generateCodeVerifier(): string {
  return crypto.randomBytes(32).toString("base64url");
}

/**
 * Derive code_challenge from code_verifier using S256 method.
 */
export function generateCodeChallenge(codeVerifier: string): string {
  return crypto
    .createHash("sha256")
    .update(codeVerifier)
    .digest("base64url");
}

/**
 * Build PKCE params (code_verifier, code_challenge, state) for a new auth request.
 */
export function buildPKCEParams(): PKCEParams {
  const code_verifier = generateCodeVerifier();
  return {
    code_verifier,
    code_challenge: generateCodeChallenge(code_verifier),
    state: crypto.randomBytes(16).toString("hex"),
  };
}

// ---------------------------------------------------------------------------
// Authorization URL builder
// ---------------------------------------------------------------------------

/**
 * Build the X OAuth 2.0 authorization URL.
 * The caller is responsible for opening this URL in a browser.
 *
 * @param clientId     X Developer App Client ID (from env: X_CLIENT_ID)
 * @param redirectUri  OAuth redirect URI (from env: OAUTH_REDIRECT_URI)
 * @param pkce         PKCE params generated by buildPKCEParams()
 */
export function buildAuthorizationUrl(
  clientId: string,
  redirectUri: string,
  pkce: PKCEParams
): string {
  const params = new URLSearchParams({
    response_type: "code",
    client_id: clientId,
    redirect_uri: redirectUri,
    scope: OAUTH_SCOPES.join(" "),
    state: pkce.state,
    code_challenge: pkce.code_challenge,
    code_challenge_method: "S256",
  });
  return `${X_OAUTH_AUTHORIZE_URL}?${params.toString()}`;
}

// ---------------------------------------------------------------------------
// Token exchange (stub — TODO: implement real HTTP request)
// ---------------------------------------------------------------------------

/**
 * Exchange an authorization_code for access_token + refresh_token.
 *
 * TODO: Replace stub with actual fetch() call to X_OAUTH_TOKEN_URL.
 *       Use Authorization: Basic base64(clientId:clientSecret) header.
 *
 * @param code         authorization_code from OAuth callback
 * @param codeVerifier PKCE code_verifier (from buildPKCEParams())
 * @param clientId     X Developer App Client ID
 * @param clientSecret X Developer App Client Secret
 * @param redirectUri  Must match the URI used in buildAuthorizationUrl()
 */
export async function exchangeCodeForTokens(
  code: string,
  codeVerifier: string,
  clientId: string,
  clientSecret: string,
  redirectUri: string
): Promise<TokenSet> {
  // TODO: Implement actual token exchange
  // Example request:
  //
  //   const resp = await fetch(X_OAUTH_TOKEN_URL, {
  //     method: "POST",
  //     headers: {
  //       "Content-Type": "application/x-www-form-urlencoded",
  //       Authorization: `Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString("base64")}`,
  //     },
  //     body: new URLSearchParams({
  //       grant_type: "authorization_code",
  //       code,
  //       redirect_uri: redirectUri,
  //       code_verifier: codeVerifier,
  //     }),
  //   });
  //   if (!resp.ok) throw new Error(`Token exchange failed: ${resp.status}`);
  //   const json = await resp.json();
  //   return {
  //     access_token: json.access_token,
  //     refresh_token: json.refresh_token,
  //     expires_at: new Date(Date.now() + json.expires_in * 1000).toISOString(),
  //   };

  void code; void codeVerifier; void clientId; void clientSecret; void redirectUri;
  throw new Error(
    "exchangeCodeForTokens is a stub. Implement the TODO above before using in production."
  );
}

// ---------------------------------------------------------------------------
// Token refresh (stub — TODO: implement real HTTP request)
// ---------------------------------------------------------------------------

/**
 * Refresh an expired access_token using the stored refresh_token.
 *
 * Called automatically by getValidAccessToken() when the stored token is expired.
 *
 * TODO: Replace stub with actual fetch() call to X_OAUTH_TOKEN_URL.
 */
export async function refreshAccessToken(
  refreshToken: string,
  clientId: string,
  clientSecret: string
): Promise<TokenSet> {
  // TODO: Implement actual token refresh
  // Example request:
  //
  //   const resp = await fetch(X_OAUTH_TOKEN_URL, {
  //     method: "POST",
  //     headers: {
  //       "Content-Type": "application/x-www-form-urlencoded",
  //       Authorization: `Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString("base64")}`,
  //     },
  //     body: new URLSearchParams({
  //       grant_type: "refresh_token",
  //       refresh_token: refreshToken,
  //       client_id: clientId,
  //     }),
  //   });
  //   if (!resp.ok) {
  //     // refresh_token has expired → signal Shell to re-authenticate
  //     throw new Error("refresh_token_expired");
  //   }
  //   const json = await resp.json();
  //   return {
  //     access_token: json.access_token,
  //     refresh_token: json.refresh_token ?? refreshToken,
  //     expires_at: new Date(Date.now() + json.expires_in * 1000).toISOString(),
  //   };

  void refreshToken; void clientId; void clientSecret;
  throw new Error(
    "refreshAccessToken is a stub. Implement the TODO above before using in production."
  );
}

// ---------------------------------------------------------------------------
// Keychain read/write (stub — TODO: use AKARI Permission API / platform Keychain)
// ---------------------------------------------------------------------------

/**
 * Retrieve stored tokens from Keychain.
 *
 * TODO: Replace with actual Keychain read via AKARI Permission API.
 *       The service name MUST match akari.toml [permissions].keychain[0].
 *
 * Example (macOS Keychain via node-keytar or @akari/sdk permission API):
 *
 *   import { permission } from "@akari/sdk";
 *   const access_token  = await permission.keychainGet(KEYCHAIN_SERVICE, KEYCHAIN_ACCOUNT_ACCESS_TOKEN);
 *   const refresh_token = await permission.keychainGet(KEYCHAIN_SERVICE, KEYCHAIN_ACCOUNT_REFRESH_TOKEN);
 *   const token_expiry  = await permission.keychainGet(KEYCHAIN_SERVICE, KEYCHAIN_ACCOUNT_TOKEN_EXPIRY);
 */
export async function loadTokensFromKeychain(): Promise<TokenSet | null> {
  // TODO: Implement Keychain read (see docstring above)
  // Return null if no tokens are stored (triggers OAuth flow in getValidAccessToken).
  void KEYCHAIN_SERVICE;
  void KEYCHAIN_ACCOUNT_ACCESS_TOKEN;
  void KEYCHAIN_ACCOUNT_REFRESH_TOKEN;
  void KEYCHAIN_ACCOUNT_TOKEN_EXPIRY;
  return null;
}

/**
 * Persist tokens to Keychain.
 *
 * TODO: Replace with actual Keychain write via AKARI Permission API.
 *
 * Example:
 *
 *   await permission.keychainSet(KEYCHAIN_SERVICE, KEYCHAIN_ACCOUNT_ACCESS_TOKEN,  tokens.access_token);
 *   await permission.keychainSet(KEYCHAIN_SERVICE, KEYCHAIN_ACCOUNT_REFRESH_TOKEN, tokens.refresh_token);
 *   await permission.keychainSet(KEYCHAIN_SERVICE, KEYCHAIN_ACCOUNT_TOKEN_EXPIRY,  tokens.expires_at);
 */
export async function saveTokensToKeychain(_tokens: TokenSet): Promise<void> {
  // TODO: Implement Keychain write (see docstring above)
}

/**
 * Remove all stored tokens from Keychain (used during revoke).
 *
 * TODO: Replace with actual Keychain delete via AKARI Permission API.
 */
export async function clearTokensFromKeychain(): Promise<void> {
  // TODO: Implement Keychain delete (see docstring above)
}

// ---------------------------------------------------------------------------
// Main entry point — get a valid access token
// ---------------------------------------------------------------------------

/**
 * Return a valid access token, refreshing automatically if expired.
 *
 * Throws if:
 *   - No tokens are stored (user needs to run OAuth flow)
 *   - Refresh token has expired (user needs to re-authenticate)
 *
 * Callers (tools.ts) catch these errors and return appropriate MCP error responses.
 */
export async function getValidAccessToken(
  clientId: string,
  clientSecret: string
): Promise<string> {
  const tokens = await loadTokensFromKeychain();

  if (!tokens) {
    throw new Error(
      "not_authenticated: No tokens found. Run the OAuth 2.0 PKCE flow first."
    );
  }

  const isExpired = new Date(tokens.expires_at) <= new Date(Date.now() + 60_000);

  if (!isExpired) {
    return tokens.access_token;
  }

  // Token expired — attempt refresh
  const refreshed = await refreshAccessToken(
    tokens.refresh_token,
    clientId,
    clientSecret
  );
  await saveTokensToKeychain(refreshed);
  return refreshed.access_token;
}
