#!/usr/bin/env node
// schemas/<protocol>/<version>/*.schema.json を protocol+version 単位でまとめて
// TypeScript 型に変換する。
// - 入力: schemas/<protocol>/<version>/*.schema.json  (複数ファイル)
// - 出力: packages/sdk-types/src/generated/<protocol>-<slug>.ts  (1 ファイル)
//   例: amp/v0.1/* → amp-v0-1.ts
// 実行: pnpm codegen（repo root）
// 運用: 生成物はコミットしてレビュー対象にする。

import {
  quicktype,
  InputData,
  JSONSchemaInput,
  FetchingJSONSchemaStore,
} from "quicktype-core";
import { readFile, writeFile, readdir, mkdir, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const schemaRoot = path.join(repoRoot, "schemas");
const outRoot = path.join(
  repoRoot,
  "packages",
  "sdk-types",
  "src",
  "generated",
);

/**
 * schemas/ を走査して [{protocol, version, files}...] を返す。
 */
async function discover() {
  const out = [];
  for (const protocol of await readdir(schemaRoot)) {
    if (protocol === "README.md") continue;
    const protoDir = path.join(schemaRoot, protocol);
    for (const version of await readdir(protoDir)) {
      const versionDir = path.join(protoDir, version);
      const files = [];
      for (const entry of await readdir(versionDir)) {
        if (!entry.endsWith(".json")) continue;
        files.push({ name: entry, path: path.join(versionDir, entry) });
      }
      if (files.length > 0) out.push({ protocol, version, files });
    }
  }
  return out;
}

/**
 * ファイル名 → quicktype に渡す top-level 型名を決める。
 * schema.json は protocol 固有のコア型に、その他は basename CamelCase。
 */
function topNameFor(protocol, fileName) {
  const coreTypeByProtocol = {
    amp: "MemoryRecord",
    m2c: "MediaContext",
  };
  if (fileName === "schema.json") {
    const core = coreTypeByProtocol[protocol];
    if (!core) {
      throw new Error(
        `Unknown protocol '${protocol}' for schema.json — add mapping in codegen.mjs`,
      );
    }
    return core;
  }
  const base = fileName.replace(/\.schema\.json$/, "").replace(/\.json$/, "");
  return base
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function outSlugFor(version) {
  // v0.1 -> v0-1
  return version.replace(/\./g, "-");
}

async function generateCombined(protocol, version, files) {
  const input = new JSONSchemaInput(new FetchingJSONSchemaStore());
  for (const file of files) {
    const topName = topNameFor(protocol, file.name);
    const schemaText = await readFile(file.path, "utf-8");
    await input.addSource({ name: topName, schema: schemaText });
  }
  const inputData = new InputData();
  inputData.addInput(input);
  const { lines } = await quicktype({
    inputData,
    lang: "typescript",
    rendererOptions: {
      "just-types": "true",
      "prefer-unions": "true",
      "explicit-unions": "true",
    },
  });
  return lines.join("\n") + "\n";
}

async function main() {
  console.log(`[codegen] schemas root: ${schemaRoot}`);
  console.log(`[codegen] out root:     ${outRoot}`);

  if (existsSync(outRoot)) {
    await rm(outRoot, { recursive: true, force: true });
  }
  await mkdir(outRoot, { recursive: true });

  const discovered = await discover();
  const indexLines = [
    "// AUTO-GENERATED by scripts/codegen.mjs — DO NOT EDIT BY HAND.",
    "// Run `pnpm codegen` at repo root to regenerate.",
    "",
  ];
  let bundleCount = 0;

  for (const { protocol, version, files } of discovered) {
    const slug = outSlugFor(version);
    const outFile = `${protocol}-${slug}.ts`;
    const outPath = path.join(outRoot, outFile);
    console.log(`  ${protocol}/${version}  (${files.length} schemas) -> ${outFile}`);
    for (const f of files) {
      console.log(`    + ${f.name}  [top: ${topNameFor(protocol, f.name)}]`);
    }
    const ts = await generateCombined(protocol, version, files);
    const header =
      `// AUTO-GENERATED from schemas/${protocol}/${version}/*.schema.json\n` +
      `// DO NOT EDIT. Run \`pnpm codegen\` at repo root to regenerate.\n` +
      `// Upstream SSOT: akari-${protocol}/spec/${version}/*.schema.json\n\n`;
    await writeFile(outPath, header + ts, "utf-8");
    indexLines.push(`export * from "./${protocol}-${slug}.js";`);
    bundleCount++;
  }

  await writeFile(
    path.join(outRoot, "index.ts"),
    indexLines.join("\n") + "\n",
    "utf-8",
  );
  console.log(`[codegen] done — ${bundleCount} bundle(s) generated + index.ts written`);
}

main().catch((err) => {
  console.error("[codegen] FAILED:", err);
  process.exit(1);
});
